name: classifier_comparison
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - libffi=3.4.4
  - libsodium=1.0.18
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - openssl=3.0.16
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pywin32=308
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - aenum==3.1.16
      - affine==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - bitsandbytes==0.46.0
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - filelock==3.18.0
      - fiona==1.10.1
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - importlib-resources==6.5.2
      - joblib==1.5.1
      - jsonargparse==4.40.0
      - jsonnet==0.21.0
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lightly==1.5.21
      - lightly-utils==0.0.2
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.5.0
      - networkx==3.2.1
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - propcache==0.3.2
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pyproj==3.6.1
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - rasterio==1.4.3
      - rich==14.0.0
      - rtree==1.4.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - shapely==2.0.7
      - simsimd==6.4.9
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - torch==2.7.1
      - torchgeo==0.5.2
      - torchmetrics==1.7.3
      - torchvision==0.22.1
      - tqdm==4.67.1
      - typeshed-client==2.7.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - yarl==1.20.1
      - zipp==3.22.0
      - docstring-parser==0.16
