name: classifier_comparison
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - h5py
  - requests
  - pillow
  - streamlit
  - tqdm
  - jupyter
  - ipykernel
  - jupyterlab
  - notebook
  - comm
  - debugpy
  - decorator
  - ipython
  - jedi
  - json5
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_pygments
  - jupyterlab_server
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook-shim
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pygments
  - pyzmq
  - terminado
  - tornado
  - traitlets
  - timm
  - networkx
  - shapely
  - pyproj
  - fiona
  - rasterio
  - rtree
  - opencv
  - anyio
  - argon2-cffi
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - brotli-python
  - certifi
  - cffi
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - defusedxml
  - einops
  - filelock
  - fonttools
  - fsspec
  - httpx
  - idna
  - importlib-metadata
  - joblib
  - jinja2
  - jsonargparse
  - jsonschema
  - kornia
  - kiwisolver
  - markupsafe
  - mistune
  - omegaconf
  - packaging
  - pandocfilters
  - platformdirs
  - protobuf
  - pyparsing
  - pyyaml
  - referencing
  - rich
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sympy
  - tensorboardx
  - threadpoolctl
  - tinycss2
  - tomli
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - zipp
  - pip
  - pip:
    - aenum
    - aiohappyeyeballs
    - aiohttp
    - aiosignal
    - async-timeout
    - frozenlist
    - multidict
    - yarl
    - lightning
    - pytorch-lightning
    - torchmetrics
    - huggingface-hub
    - safetensors
    - segmentation-models-pytorch
    - lightly
    - lightly-utils
    - eval-type-backport
    - hydra-core
    - jsonnet
    - kornia-rs
    - propcache
    - pydantic
    - pydantic-core
    - simsimd
    - stringzilla
    - typeshed-client
    - typing-inspection
    - tzdata
    - torchgeo==0.5.2
    - docstring-parser