name: classifier_comparison
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - babel=2.16.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - cpython=3.9.23
  - datasets=3.3.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - flit-core=3.12.0
  - fqdn=1.5.1
  - gflags=2.2.2
  - glog=0.5.0
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.31.2
  - hyperframe=6.1.0
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libkrb5=1.21.3
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multiprocess=0.70.15
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openssl=3.0.17
  - orc=2.1.1
  - overrides=7.4.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytz=2025.2
  - pywin32=308
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - safetensors=0.5.3
  - send2trash=1.8.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - tomli=2.0.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - types-python-dateutil=2.9.0.20250809
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vcomp14=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.5
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xxhash=0.8.0
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aenum==3.1.16
      - affine==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - bitsandbytes==0.46.0
      - blinker==1.9.0
      - cachetools==6.1.0
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - docstring-parser==0.16
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - filelock==3.18.0
      - fiona==1.10.1
      - fonttools==4.58.2
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - joblib==1.5.1
      - jsonargparse==4.40.0
      - jsonnet==0.21.0
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lightly==1.5.21
      - lightly-utils==0.0.2
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.5.0
      - narwhals==2.1.1
      - networkx==3.2.1
      - numpy==2.0.2
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pandas==2.3.0
      - pillow==11.2.1
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - pyproj==3.6.1
      - pytorch-lightning==2.5.2
      - rasterio==1.4.3
      - rich==14.0.0
      - rtree==1.4.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - shapely==2.0.7
      - simsimd==6.4.9
      - smmap==5.0.2
      - streamlit==1.48.1
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - toml==0.10.2
      - torch==2.7.1
      - torchgeo==0.5.2
      - torchmetrics==1.7.3
      - torchvision==0.22.1
      - typeshed-client==2.7.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - watchdog==6.0.0
      - yarl==1.20.1
      - zipp==3.22.0