name: cnn_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ca-certificates
  - openssl
  - pip
  - setuptools
  - sqlite
  - vc  # Remove on linux
  - vs2015_runtime  # Remove on linux
  - wheel
  - pip:
    - aenum==3.1.16
    - affine==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - altair==5.5.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - bitsandbytes==0.45.5
    - blinker==1.9.0
    - cachetools==5.5.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.1.8
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - docstring-parser==0.16
    - einops==0.8.1
    - filelock==3.18.0
    - fiona==1.10.1
    - fonttools==4.58.0
    - frozenlist==1.6.0
    - fsspec==2025.3.2
    - gitdb==4.0.12
    - gitpython==3.1.44
    - huggingface-hub==0.31.1
    - hydra-core==1.3.2
    - idna==3.10
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - jsonargparse==4.39.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.7
    - kornia==0.8.1
    - kornia-rs==0.1.9
    - lightly==1.5.20
    - lightly-utils==0.0.2
    - lightning==2.5.1.post0
    - lightning-utilities==0.14.3
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.4.3
    - narwhals==1.39.0
    - networkx==3.2.1
    - numpy==2.0.2
    - omegaconf==2.3.0
    - opencv-python==4.11.0.86
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.2.1
    - propcache==0.3.1
    - protobuf==6.30.2
    - pyarrow==20.0.0
    - pydantic==2.11.4
    - pydantic-core==2.33.2
    - pydeck==0.9.1
    - pygments==2.19.1
    - pyparsing==3.2.3
    - pyproj==3.6.1
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.1.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - rasterio==1.4.3
    - referencing==0.36.2
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.24.0
    - rtree==1.4.0
    - safetensors==0.5.3
    - segmentation-models-pytorch==0.5.0
    - shapely==2.0.7
    - six==1.17.0
    - smmap==5.0.2
    - streamlit==1.45.0
    - sympy==1.14.0
    - tenacity==9.1.2
    - tensorboardx==2.6.2.2
    - timm==1.0.15
    - toml==0.10.2
    - torch==2.7.0
    - torchgeo==0.5.2
    - torchmetrics==1.7.1
    - torchvision==0.22.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - typeshed-client==2.7.0
    - typing-extensions==4.13.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - watchdog==6.0.0
    - yarl==1.20.0
    - zipp==3.21.0